### ISSUE TITLE
乐观锁和ttl未生效

### ISSUE THREAD

**Issue by wxbacy** [krissss/webman-lock#2]
![image](https://user-images.githubusercontent.com/20201380/197488384-3fbc41dc-fbd9-4084-b433-bef40121a7c6.png)
设置blocking = true, 并且指定了ttl = 5,连续发起两次请求，都等待了10s执行成功了
![image](https://user-images.githubusercontent.com/20201380/197488683-4448ee7b-693a-474a-8205-2d8483c06158.png)

**Comment by krissss** [comment]
sleep 在 webman 里是阻塞进程的，会导致代码无法执行的，不要使用 sleep 测试

可以使用读取一个大文件、或者弄个很慢的sql啥的来模拟

**Comment by wxbacy** [comment]
ok 我再测试下

**Comment by wxbacy** [comment]
![image](https://user-images.githubusercontent.com/20201380/197491247-f8542595-dd17-48f2-8b7b-737ead7cf6e1.png)
改成操作数据库也是等了几十秒两个都成功了

**Comment by wxbacy** [comment]
用的storege是redis

**Comment by krissss** [comment]
好像是个大问题

**Comment by krissss** [comment]
目前测试是 linux 多进程模式下可以触发，但是仍然会存在当请求被分配到相同进程时会进入等待
该问题比较大，我想想有没有办法解决

**Comment by wxbacy** [comment]
嗯 我大概get到是怎么回事了，应该另一个请求都一直在wait，还没执行任何代码

**Comment by krissss** [comment]
不过想来其实也没啥问题，问题主要是 blocking 会使用 usleep 导致进程阻塞
因为本身就不是 locker 的问题，是 workman 下 sleep 导致了进程阻塞，是请求进不来
那正常我们的业务 try finally 中或者之前，肯定是会判断业务状态的吧，所以也不太影响实际的业务使用

**Comment by wxbacy** [comment]
嗯，不过有点奇怪，我的开发环境webman有8个worker进程，每次测试两个请求都是进一个worker所以阻塞着？

**Comment by krissss** [comment]
windows?

**Comment by wxbacy** [comment]
windows docker

**Comment by krissss** [comment]
我自己测试的 wsl 环境和 `krisss/docker-webman` docker 镜像中开两个 webman 进程，都是可以两个请求分到两个worker的

**Comment by wxbacy** [comment]
我换成两个不同的接口就可以测试到不同的进程了
