### ISSUE TITLE
请问估计这个比数据库的锁能快多少呢？

### ISSUE THREAD

**Issue by leamus** [krissss/webman-lock#3]
感觉上Redis锁应该比数据库的乐观和悲观锁要快，但不知能快多少呢？

**Comment by krissss** [comment]
应用场景不一样吧，没法完全界定谁快谁慢呢
另外上锁快慢无关紧要，重要的是数据是否真的能锁住的问题

**Comment by leamus** [comment]
一般也就数据库需要加锁啊，所以就针对数据库插入/修改慢的情况下做个小比较；
Redis是在访问上加锁，不进入数据库，而数据库上的锁靠数据库内部机制，还有可能会造成死锁，所以我感觉Redis锁应该比数据库的要快些~
